version: '3'
services:
  envoy:
    image: envoyproxy/envoy:dev-7d8791802c1d7e0230752e3d3b2c29b6c0621bc7
    ports:
      - "9901:9901"
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml